http:
  port: "8081"
  
american:
  host: "training4-american-api-favaz.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "8e97caf2d4c84dc7b71b32f6d14c9904"
  client_secret: "973737b603684b1DB2f90304157285d9"
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
